SELECT `STUDENT_ID`, `PASSWORD`
FROM student
WHERE room_id = 'A227'

SELECT t.`TUTOR_ID`, t.`TUTOR_PASSWORD`
FROM tutor AS t
JOIN floor AS f ON t.`TUTOR_ID` = f.`TUTOR_ID`
WHERE f.`BUILDING_ID` = 'A'
  AND f.`FLOOR_ID` = '2';

SELECT w.`WARDEN_ID`, w.`WARDEN_PASSWORD`
FROM warden AS w
JOIN building AS b ON w.`WARDEN_ID` = b.`WARDEN_ID`
WHERE b.`BUILDING_ID` = 'A';

SELECT * FROM student WHERE `STUDENT_ID`=194279205;

SELECT * FROM room AS r
JOIN student s ON r.`ROOM_ID` = s.`ROOM_ID`
WHERE s.`STUDENT_ID` = 194279205;

SELECT * FROM tutor WHERE `TUTOR_ID`=176542389;

SELECT * FROM warden WHERE `WARDEN_ID`=189235647;