CREATE TABLE warden(
        WARDEN_ID INT PRIMARY KEY,
        WARDEN_NAME VARCHAR(50),
        WARDEN_PHONE_NUM VARCHAR(50),
        WARDEN_EMAIL_ADDRESS VARCHAR(50),
        WARDEN_PASSWORD INT
    );

CREATE TABLE building(
        BUILDING_ID VARCHAR(50) PRIMARY KEY,
        WARDEN_ID INT,
        FOREIGN KEY (WARDEN_ID) REFERENCES warden(WARDEN_ID)
    );

CREATE TABLE tutor(
        TUTOR_ID INT PRIMARY KEY,
        TUTOR_NAME VARCHAR(50),
        TUTOR_PHONE_NUM VARCHAR(50),
        TUTOR_EMAIL_ADDRESS VARCHAR(50),
        TUTOR_PASSWORD INT,
        TUTOR_TBPROCESSED_REQ_NUM INT
    );

CREATE TABLE floor(
        BUILDING_ID VARCHAR(50),
        FLOOR_ID INT,
        TUTOR_ID INT,
        FLOOR_GENDER VARCHAR(50),
        PRIMARY KEY (BUILDING_ID, FLOOR_ID),
        FOREIGN KEY (BUILDING_ID) REFERENCES building(BUILDING_ID),
        FOREIGN KEY (TUTOR_ID) REFERENCES tutor(TUTOR_ID)
    );

CREATE TABLE room(
        ROOM_ID VARCHAR(50) PRIMARY KEY,
        BUILDING_ID VARCHAR(50),
        FLOOR_ID INT,
        IS_EMPTY INT,
        ELECTRICITY_BALANCE FLOAT(50),
        REQ_TBPROCESSED_NUM INT,
        REQ_HBPROCESSED_NUM INT,
        FOREIGN KEY (BUILDING_ID, FLOOR_ID) REFERENCES floor(BUILDING_ID, FLOOR_ID)
    );

CREATE TABLE bed(
        ROOM_ID VARCHAR(50),
        BED_ID VARCHAR(50),
        AVAILABILITY INT,
        PRIMARY KEY (ROOM_ID, BED_ID),
        FOREIGN KEY (ROOM_ID) REFERENCES room(ROOM_ID)
    );

CREATE TABLE student(
        STUDENT_ID INT PRIMARY KEY, 
        STUDENT_NAME VARCHAR(50),
        BUILDING_ID VARCHAR(50),
        FLOOR_ID VARCHAR(50),
        ROOM_ID VARCHAR(50),
        BED_ID VARCHAR(50),
        GENDER VARCHAR(50),
        STUDENT_PHONE_NUM VARCHAR(50),
        MAJOR VARCHAR(50),
        SCHOOL VARCHAR(50),
        STUDENT_EMAIL_ADDRESS VARCHAR(50),
        PASSWORD INT,
        FOREIGN KEY (ROOM_ID, BED_ID) REFERENCES bed(ROOM_ID, BED_ID)
    );

SELECT s.BUILDING_ID, s.FLOOR_ID, s.ROOM_ID, s.BED_ID, r.ELECTRICITY_BALANCE 
                 FROM student s
                 JOIN room r ON s.ROOM_ID = r.ROOM_ID 
                 WHERE s.STUDENT_ID = 112874695

SELECT  F.FLOOR_ID, T.TUTOR_ID, T.TUTOR_NAME, T.TUTOR_PHONE_NUM, T.TUTOR_GENDER, T.TUTOR_TBPROCESSED_REQ_NUM
        FROM tutor T
        JOIN floor F ON T.TUTOR_ID = F.TUTOR_ID
        WHERE F.BUILDING_ID = 'A'
        GROUP BY  F.FLOOR_ID, T.TUTOR_ID, T.TUTOR_NAME, T.TUTOR_PHONE_NUM, T.TUTOR_GENDER, T.TUTOR_TBPROCESSED_REQ_NUM
        ORDER BY F.FLOOR_ID

SELECT S.STUDENT_ID, S.STUDENT_NAME, S.GENDER, S.SCHOOL, S.MAJOR, S.STUDENT_PHONE_NUM, S.ROOM_ID, S.BED_ID
                          FROM student S
                          WHERE S.BUILDING_ID = 'A'
                          ORDER BY S.ROOM_ID, S.BED_ID

SELECT R.ROOM_ID, R.FLOOR_ID,R.ELECTRICITY_BALANCE, 
                       (SELECT COUNT(*) FROM bed B WHERE B.ROOM_ID = R.ROOM_ID AND B.AVAILABILITY = 1) AS MAX_CAPACITY,
                       COUNT(S.STUDENT_ID) AS Occupied_Beds
                       FROM room R
                       LEFT JOIN student S ON R.ROOM_ID = S.ROOM_ID
                       WHERE R.BUILDING_ID = 'A'
                       GROUP BY R.ROOM_ID, R.FLOOR_ID, R.ELECTRICITY_BALANCE
                       ORDER BY R.ROOM_ID

SELECT (SELECT COUNT(*) FROM bed B 
        WHERE B.ROOM_ID IN (SELECT ROOM_ID FROM room WHERE BUILDING_ID = 'A')) AS Total_Beds,
        (SELECT COUNT(*) FROM student S 
        WHERE S.BUILDING_ID = 'A') AS Occupied_Beds

SELECT t.TUTOR_ID, f.BUILDING_ID, f.FLOOR_ID
                       FROM tutor t
                       JOIN floor f ON t.TUTOR_ID = f.TUTOR_ID
                       JOIN room r ON r.FLOOR_ID = f.FLOOR_ID AND r.BUILDING_ID = f.BUILDING_ID
                       WHERE r.ROOM_ID ='A203';

        SELECT S.STUDENT_ID, S.STUDENT_NAME, S.ROOM_ID
        FROM student S
        JOIN room R ON S.ROOM_ID = R.ROOM_ID
        JOIN floor F ON R.FLOOR_ID = F.FLOOR_ID
        WHERE F.TUTOR_ID = 176542389 AND R.REQ_TBPROCESSED_NUM > 0
        ORDER BY R.ROOM_ID, S.STUDENT_ID

UPDATE tutor SET TUTOR_TBPROCESSED_REQ_NUM = TUTOR_TBPROCESSED_REQ_NUM - 1,
                TUTOR_HBPROCESSED_REQ_NUM = TUTOR_HBPROCESSED_REQ_NUM + 1
                WHERE TUTOR_ID = 176542389

SELECT BUILDING_ID FROM student WHERE STUDENT_ID =112874695

SELECT ROOM_ID
                 FROM room
                 WHERE BUILDING_ID='A' AND FLOOR_ID=2 AND IS_EMPTY=1

SELECT ar.REQUEST_ID, s.STUDENT_ID, s.STUDENT_NAME, ar.BUILDING_ID, ar.FLOOR_ID, ar.ROOM_ID, ar.BED_ID
                        FROM adjust_request ar
                        JOIN student s ON ar.STUDENT_ID = s.STUDENT_ID
                        JOIN floor f ON ar.FLOOR_ID = f.FLOOR_ID AND ar.BUILDING_ID = f.BUILDING_ID
                        WHERE f.TUTOR_ID=187654923

UPDATE student SET BUILDING_ID='A', FLOOR_ID=4, ROOM_ID='A409', BED_ID='B'
                                WHERE STUDENT_ID=112874695

UPDATE room SET REMAIN_BEDS = REMAIN_BEDS - 1 WHERE ROOM_ID ='A203'

UPDATE room SET IS_EMPTY = 0 WHERE ROOM_ID = 'A203'